### PR TITLE
Major refactoring, 

### PR DESCRIPTION
**Pull request by dkrainyk**
Added Pub-Sub (`TinyMesenger`) lib and IOC (`Autofac`) to decouple different parts of UI and service from each other.
Introduced Common shared library to reuse code for both service and desktop app.
Used `ImpromptuInterface` lib to simplify work with reflection in service.
Fixed issues #1 and #2
Kept the main idea of config, logger format and named pipes messages format.
Moved from global hooks to activity check timer (`GetLastInputInfo(ref LASTINPUTINFO plii)`), because hooks don't work on elevated windows unless user launches settings app as administrator. Checks every 300ms for last user activity.

### CODE REVIEW

**Comment by JooJooBee666** [comment]
Also, with all these changes, the backlight does NOT come back on after resuming from screen blank nor when the service is first started, therefor I will not release this build just yet until these issues are resolved.  I'm still trying to figure out what all was done here and why these items aren't working at this point.

**Comment by dkrainyk** [comment]
What are your settings? 
It should work for resume from sleep. I'm personally use user activity tracking though, so this might work differently in other modes.

**Comment by JooJooBee666** [comment]
It appears that the callback on power change states is not working.  Though debug logging is enabled, there is nothing logged about power state changes.  I left Visual Studio attached to the service debugging throughout the day.  Not once did my break points come up.  Still trying to wrap my head around these changes.  I've never used Autofac, TinyMessengerHub or builder so struggling to follow along with it right now.

Here's my config settings tho:

<Keyboard_Core_Path>C:\ProgramData\Lenovo\ImController\Plugins\ThinkKeyboardPlugin\x86\Keyboard_Core.dll</Keyboard_Core_Path>
<Light_Level>2</Light_Level>
<Timeout_Preference>0</Timeout_Preference>
<Enable_Debug_Log>true</Enable_Debug_Log>
<Save_Backlight_State>true</Save_Backlight_State>
<Saved_State>2</Saved_State>

**Comment by dkrainyk** [comment]
I eliminated all custom energy tracking code because service class contains everything out of the box.
You can check `CustomServiceBase.cs` `OnPowerEvent` method.
I did check and service enables backlight after resuming from sleep.
Are you running service as windows service or simply as console app in visual studio? I believe second option will not receive power notifications from system. 
If you want to debug service - you need to install debug version as windows service and attach debugger after starting it normally.

**Comment by JooJooBee666** [comment]
Yeah, that's exactly how I've been debugging this app up to this point ;)  This is how I know that the activate backlight is not being called when I wake the monitor.  I set a breakpoint on  **switch (powerStatus)** on line 64, but it never gets hit when I wake the monitor up.

**Comment by dkrainyk** [comment]
Ok, that might be situation I didn't count in. 
So display off != sleep, therefore no power notification...

Lets try this:
uncomment this line: https://github.com/JooJooBee666/LBCService/blob/master/LBCService/Program.cs#L20
then add subscription to `PowerStateMessage` here:
https://github.com/JooJooBee666/LBCService/blob/master/LBCService/BacklightControls.cs#L45
something like:
`_subToPower = _hub.Subscribe<PowerStateMessage>(_ => 
{
    if(_.IsDisplayOn) 
        ActivateBacklight(data.LightLevel);
});`

Dont forget to unsub in `Clear` method

**Comment by JooJooBee666** [comment]
Yeah, I noticed that myself.  I seem to recall something similar a while back when I started this and I believe that's how I ended up with the alternate method I was using.  It's now picking up the state change...but was confused about the previous state.  Then after a few tries, it crashed with the following error:
`Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`
on ServiceBase.Run(servicesToRun);

**Comment by dkrainyk** [comment]
I didn't change how that class interacts with win32, so probably that is a reason why your version of service crashed silently sometimes. 
I'll take a look this evening to find a way to get that display notification without crashing.

**Comment by JooJooBee666** [comment]
Yeah, I was just wondering the same thing.  I was never able to catch the crash myself though.  I'll look a bit deeper myself as well.

**Comment by dkrainyk** [comment]
As a temporary workaround you can simply set Timeout_Preference to some value above 0 to enable user activity tracking and it will enable backlight once you interact with laptop to turn on display.

**Comment by JooJooBee666** [comment]
So I have not been able to reproduce the crash since that one time with the enabling of the additional power management methods.  I'm thinking maybe to add that as an option to config for now at least.  Enable the advanced power management at risk of crashing, or just use the input tracking for stability.  I haven't been able to find another way to register for the power events without using the pinvokes and I don't have the skill to figure why that method is unstable.  It's the only way I can find to do it :/

I'll work on adding these changes this coming week and push out a build with it.  Any further suggestions from you are more than welcome in the meantime. :)

**Comment by dkrainyk** [comment]
I would vote against using that :) This pinvoke (RegisterPowerSettingNotification in User32) prevents service from receiving proper control messages (like stop, etc.)
I've found alternative method ([PowerSettingRegisterNotification](https://docs.microsoft.com/en-us/windows/desktop/api/powersetting/nf-powersetting-powersettingregisternotification) in Powrprof.dll) but I'm not aware of its signature and how to use it and whether it is possible to use it from service app. 
Probably it is a good idea to move it to the settings app since desktop apps can monitor such things easier.
Also I'm going to implement actual backlight state monitor and send it over to settings app, it might be useful to know 'real' state.

**Comment by JooJooBee666** [comment]
I'm definitely not opposed to using another method to get the power state, but as I mentioned, I was unable to find any other one that worked.

Regarding getting the actual state, I tried that too but I was never able to get the Keyboard_Core.dll GetKeyboardBackLightLevel or GetKeyboardBackLightLevel methods to report the proper states.  They always gave me a 0.  I believe the issue was that calls are made out of context (i.e. the state is only known within the active system loaded dll) and the only way to properly get it is to call the method from the loaded library as opposed to just calling the method from the dll directly.

I'll do some additional research this week to see if there is another, more stable, way to get the state and I'll hold off on my previous suggested changes.

**Comment by dkrainyk** [comment]
Good news:
I've managed to receive display state via `PowerSettingRegisterNotification` from `Powprof`
So I'll move that to the settings app and will fire notifications to turn on backlight.
Also take a look at https://github.com/JooJooBee666/LBCService/blob/master/LBCService/BacklightControls.cs#L82
That is how I'm currently getting backlight state. It worked last time I've checked.

**Comment by dkrainyk** [comment]
Just created `PR` #4 
Please check it out.
Now it monitors display state from the settings app using newly discovered win32 api.
Also there is a new backlight checker thread in service that sends it to the app which in its turn displays current backlight level to you.

**Pull request merged**
